FROM immortalwrt:base

LABEL maintainer="Tianling Shen <cnsztl@immortalwrt.org>"

COPY --chown=build:build ./sdk /home/build/immortalwrt
RUN chown build:build /home/build/immortalwrt/

USER build
ENV HOME=/home/build
WORKDIR /home/build/immortalwrt/
